package com.pgmit.tptt.constant;

public interface APIConstant {

	String DELETE_SUCCESS = "Record Deleted Success !!";
	String DELETE_FAIL = "Record Can not be Deleted !! try again";

	String MAIL_SEND_SUCCESS = "Mail send Success";
	String MAIL_SEND_FAIL = "Mail send Failed !!";

	String STUDENT_PWD_MAIL_SUBJECT = "Autogenerated password for login";
	String STUDENT_PWD_MAIL_FROM = "sudarshan.nagre99@gmail.com";

	int PASSWORD_LENGTH = 8;
	
	String STUDENT_REGISTRATION_SUCCESS = "Registration Success !!!!";
	String STUDENT_REGISTRATION_FAIL = "Registration Failed , try again !!";
}
